name: Flask app actions
on: [push]
jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:
      - run: python -V
      - run: docker --version
  Second-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Installing libs
        run: pip install -r requirements.txt
      - name: Testing app.py
        run: pylint app.py
  Third-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Building docker image
        run: docker build --tag test-flask-app .
